### PR TITLE
Update for node 0.10.x and 0.12.x

### PR DESCRIPTION
**Pull request by ifraixedes**
I updated the devDependencies to be able to run the test in node 0.12; I also checked with node 0.10 and 0.11 and it works, so I updated the engines to specify that range.

Bear in mind that I haven't bumped the package version, you should do to avoid to break packages which depend of it and they are still running with old node versions. Not sure if you should bump the package to major or minor, I guess that major should be reliable not break dependant packages.

### CODE REVIEW

**Comment by personalcomputer** [comment]
Thanks for the maintenance Ifraixedes! I'm not too concerned about following semantic versioning here, but I appreciate your concern.

**Comment by ifraixedes** [comment]
Thanks to merge the PR, however you must bump the version of the package at least, the minor, and after update push the new version to npm, otherwise people couldn't use with the current node production version.

On the other hand, I kept the engines field in `package.json` because it was there, nonetheless, from my point of view, I would remove it, because I cannot see any node dependency in this library, but I may be wrong because I've only taken a quick glance.

**Comment by personalcomputer** [comment]
Right, thanks. I haven't used node for over two years, not the best person to be maintaining this.

**Comment by personalcomputer** [comment]
I've notified the maintainer of the npm package, and further gone head and asked him if he would maintain smaz.js, in place of my incompetence.

Thanks again for brining this to my attention, ifralxedes.

**Comment by ifraixedes** [comment]
OK, can you open an issue until you figure out if he'll continue maintaining the module; I think that people who arrive to this repository should be aware of the current status, therefore an open issue would warn them and they can take better decision if to use it or not.

Thanks to take care of it.

**Comment by personalcomputer** [comment]
I don't think that is necessary, the js itself works.

**Pull request merged**
